server:
  port: 8088

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/tech_support_scheduler
    username: tech
    password: tech
    hikari:
      maximum-pool-size: 10

mybatis:
  mapper-locations: classpath:sqlmapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
