--- # Configuration Port
server:
  port: 8088

--- # Configuration Thymeleaf
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

--- # Configuration Devtools
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

#--- # Configuration MariaDb
#spring:
#  datasource:
#    #driver-class-name: org.mariadb.jdbc.Driver
#    #url: jdbc:mariadb://localhost:3307/boot
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:log4jdbc:mariadb://localhost:3307/boot
#    username: boot
#    password: boot
#    hikari:
#      maximum-pool-size: 10

#--- # Configuration mybatis
#mybatis:
#  mapper-locations: classpath:sqlmapper/**/*.xml
## mybatis.configuration.map-underscore-to-camel-case=true

... # End